
name: "user-srv"

user_srv:
  host: "localhost"
  port: 8082

mysql:
  host: "localhost"
  port: 3306
  name: "sales_user_srv"
  user: "root"
  password: "701XTAY1993"

consul:
  host: "127.0.0.1"
  port: "8500"